spring:
  application:
    name: academic-management-reporter
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-1.0.xml
    url: jdbc:h2:mem:myDB;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE